#!/bin/bash

## function to check if a process is alive and running:

_isRunning() {
    ps -o comm= -C "$1" 2>/dev/null | grep -x "$1" >/dev/null 2>&1
}

if ! _isRunning engieAcceptTest; then
    "${HOME}/workspace/engieAcceptTest/engieAcceptTest" &
fi

