#!/bin/bash

id="0"


check_process_running()
{
    id=`ps aux | grep engieAcceptTest | grep -v grep | awk ' { print $2 }'`
    echo ${id}
}

entry()
{
    check_process_running
    if [ -z $id ] ; then
        ${HOME}/workspace/engieAcceptTest/engieAcceptTest
    fi
}

# check if process running and if not running restart it.
echo "running mdWatchdog"
entry


